// Autogenerated!!!
// don't modify this file!!!

#include "simpletest.h"

void SimpleTest_AnalogInput(void);
void SimpleTest_Analog2(void);

void handlerSimpleTest(int a)
{
	printf("Section %i: %sSignal %i!%s Exit\n", rSimpleTest::Instance().m_curSection, S_TEXT_FAULT(rSimpleTest::Instance().isColored()), a, S_TEXT_RESET(rSimpleTest::Instance().isColored()));
	exit(1);
}

rSimpleTest::rSimpleTest(void)
{
	m_tests.push_back(new rItemType("AnalogInput", "testing analog input. IO simulate", &SimpleTest_Descr_AnalogInput));
	m_tests.push_back(new rItemType("Analog2", "testing analog signals 2222", &SimpleTest_Descr_Analog2));
}
