// Autogenerated!!!
// don't modify this file!!!

#include "simpletest.h"

void SimpleTest_AnalogInput(void);
void SimpleTest_Analog2(void);


rSimpleTest::rSimpleTest(void)
{
	m_tests.push_back(new rItemType("AnalogInput", "testing analog input. IO simulate", &SimpleTest_AnalogInput));
	m_tests.push_back(new rItemType("Analog2", "testing analog signals 2222", &SimpleTest_Analog2));
}
