#ifndef TTTERM_VERSION_H
#define TTTERM_VERSION_H

#define TTTERM_VERSION_MAJOR 0
#define TTTERM_VERSION_MINOR 4
#define TTTERM_VERSION_PATCH 0
#define TTTERM_VERSION_BUILD 391
#define TTTERM_VERSION_META ""
#define TTTERM_VERSION "0.4.0.391"
#define TTTERM_COMPILE_DATE "2020-03-28"
#define TTTERM_COMPILE_TIME "19:17:34"

#endif /* TTTERM_VERSION_H */
