//=================================================================================================
//===
//=== text_id.h
//===
//=== Copyright (c) 2019 by RangeSoft.
//=== All rights reserved.
//===
//=== Litvinov "VeduN" Vitaliy O.
//===
//=================================================================================================
//===
//=== Идентификаторы стандартных строк
//===
//=================================================================================================

#pragma once

#include "def.h"


enum STRINGID
{
	// Строки до 1000 являются единицами измерения, и представлены в UNITID (units.h)

	SID_PRESENT = 1000,
	SID_PHYSICAL,
	SID_CURRENT,
	SID_TEMPERATURE,
	SID_PRESSURE,
	SID_PERIOD,
	SID_DENSITY,
	SID_DENSITY15,
	SID_DENSITY20,
	SID_B,
	SID_B15,
	SID_Y,
	SID_Y15,
	SID_CTL,
	SID_CPL,
	SID_IMPULSE,
	SID_FREQUENCY,
	SID_FLOWRATE_MASS,
	SID_FLOWRATE_VOLUME,
	SID_FLOWRATE_VOLUME15,
	SID_FLOWRATE_VOLUME20,
	SID_VALUE,
	SID_CANFILLED,

	SID_SEL_OUT = 1500,
	SID_SEL_IN1,
	SID_SEL_IN2,
	SID_SEL_IN3,
	SID_SEL_IN4,
	SID_SEL_FLT1,
	SID_SEL_FLT2,
	SID_SEL_FLT3,
	SID_SEL_FLT4,
	SID_SEL_GRP1_IN1,
	SID_SEL_GRP1_IN2,
	SID_SEL_GRP1_IN3,
	SID_SEL_GRP1_IN4,
	SID_SEL_GRP2_IN1,
	SID_SEL_GRP2_IN2,
	SID_SEL_GRP2_IN3,
	SID_SEL_GRP2_IN4,
	SID_SEL_GRP3_IN1,
	SID_SEL_GRP3_IN2,
	SID_SEL_GRP3_IN3,
	SID_SEL_GRP3_IN4,
	SID_SEL_GRP4_IN1,
	SID_SEL_GRP4_IN2,
	SID_SEL_GRP4_IN3,
	SID_SEL_GRP4_IN4,
	SID_SEL_GRP5_IN1,
	SID_SEL_GRP5_IN2,
	SID_SEL_GRP5_IN3,
	SID_SEL_GRP5_IN4,
	SID_SEL_GRP6_IN1,
	SID_SEL_GRP6_IN2,
	SID_SEL_GRP6_IN3,
	SID_SEL_GRP6_IN4,
	SID_SEL_GRP7_IN1,
	SID_SEL_GRP7_IN2,
	SID_SEL_GRP7_IN3,
	SID_SEL_GRP7_IN4,
	SID_SEL_GRP8_IN1,
	SID_SEL_GRP8_IN2,
	SID_SEL_GRP8_IN3,
	SID_SEL_GRP8_IN4,
	SID_SEL_GRP1_FLT1,
	SID_SEL_GRP1_FLT2,
	SID_SEL_GRP1_FLT3,
	SID_SEL_GRP1_FLT4,
	SID_SEL_GRP2_FLT1,
	SID_SEL_GRP2_FLT2,
	SID_SEL_GRP2_FLT3,
	SID_SEL_GRP2_FLT4,
	SID_SEL_GRP3_FLT1,
	SID_SEL_GRP3_FLT2,
	SID_SEL_GRP3_FLT3,
	SID_SEL_GRP3_FLT4,
	SID_SEL_GRP4_FLT1,
	SID_SEL_GRP4_FLT2,
	SID_SEL_GRP4_FLT3,
	SID_SEL_GRP4_FLT4,
	SID_SEL_GRP5_FLT1,
	SID_SEL_GRP5_FLT2,
	SID_SEL_GRP5_FLT3,
	SID_SEL_GRP5_FLT4,
	SID_SEL_GRP6_FLT1,
	SID_SEL_GRP6_FLT2,
	SID_SEL_GRP6_FLT3,
	SID_SEL_GRP6_FLT4,
	SID_SEL_GRP7_FLT1,
	SID_SEL_GRP7_FLT2,
	SID_SEL_GRP7_FLT3,
	SID_SEL_GRP7_FLT4,
	SID_SEL_GRP8_FLT1,
	SID_SEL_GRP8_FLT2,
	SID_SEL_GRP8_FLT3,
	SID_SEL_GRP8_FLT4,
	SID_SEL_GRP1_OUT,
	SID_SEL_GRP2_OUT,
	SID_SEL_GRP3_OUT,
	SID_SEL_GRP4_OUT,
	SID_SEL_GRP5_OUT,
	SID_SEL_GRP6_OUT,
	SID_SEL_GRP7_OUT,
	SID_SEL_GRP8_OUT,

	SID_UNKNOW = 0xFFFFFFFF
};
