#ifndef TRITONN_VERSION_H
#define TRITONN_VERSION_H

#define TRITONN_VERSION_MAJOR 0
#define TRITONN_VERSION_MINOR 17
#define TRITONN_VERSION_PATCH 0
#define TRITONN_VERSION_BUILD 2968
#define TRITONN_VERSION_META ""
#define TRITONN_VERSION "0.17.0.2968"
#define TRITONN_COMPILE_DATE "2020-08-22"
#define TRITONN_COMPILE_TIME "02:41:53"
#define TRITONN_COMPILE_UNIX 1598046113

#endif /* TRITONN_VERSION_H */
