#ifndef TRITONN_VERSION_H
#define TRITONN_VERSION_H

#define TRITONN_VERSION_MAJOR 0
#define TRITONN_VERSION_MINOR 17
#define TRITONN_VERSION_PATCH 0
#define TRITONN_VERSION_BUILD 3155
#define TRITONN_VERSION_META ""
#define TRITONN_VERSION "0.17.0.3155"
#define TRITONN_COMPILE_DATE "2020-10-03"
#define TRITONN_COMPILE_TIME "20:24:34"
#define TRITONN_COMPILE_UNIX 1601738674

#endif /* TRITONN_VERSION_H */
