#ifndef TRITONN_VERSION_H
#define TRITONN_VERSION_H

#define TRITONN_VERSION_MAJOR 0
#define TRITONN_VERSION_MINOR 17
#define TRITONN_VERSION_PATCH 0
#define TRITONN_VERSION_BUILD 2976
#define TRITONN_VERSION_META ""
#define TRITONN_VERSION "0.17.0.2976"
#define TRITONN_COMPILE_DATE "2020-09-21"
#define TRITONN_COMPILE_TIME "03:10:02"
#define TRITONN_COMPILE_UNIX 1600639802

#endif /* TRITONN_VERSION_H */
