# create .bin file

if(CMAKE_TRITONN_YOCTO)
	set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_BUILD}.${PROJECT_VERSION_HASH}")
	set(CPACK_TRITONN_FILENAME "${PROJECT_NAME}_${CPACK_PACKAGE_VERSION}")
	set(CPACK_GENERATOR "ZIP")
	set(CPACK_SET_DESTDIR ON)
	set(CPACK_PACKAGE_FILE_NAME "CPACK_TRITONN_FILENAME")
	set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)

	include(CPack)

	add_custom_target(package_ssl
		COMMAND openssl enc -e -aes256 -pbkdf2 -k Kx48dHnZ@o3nE8L%pfNu3V9rM8g@n7 -in ${CPACK_TRITONN_FILENAME}.zip -out ${CPACK_TRITONN_FILENAME}.bin
		DEPENDS package
	)

endif()
