# create .bin file

if(TRITONN_YOCTO)
	set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_BUILD}.${PROJECT_VERSION_HASH}")
	set(CPACK_GENERATOR "GZIP")
	set(CPACK_SET_DESTDIR ON)
	set(CPACK_PACKAGE_DIRECTORY "")
	set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}_${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_BUILD}.${PROJECT_VERSION_HASH}")
	set(CPACK_PACKAGE_INSTALL_DIRECTORY "")
	set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)

	include(CPack)

	add_custom_target(package COMMAND
		"openssl enc -e -pdkbf2 -k Kx48dHnZ@o3nE8L%pfNu3V9rM8g@n7 -in ${} -out ${}")
	add_dependencies(package_ssl package)
endif()
